[package]
name = "binarize_images"
version = "0.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.6"
clap = { version = "4.5.1", features = ["derive"] }
imageproc = "0.25.0"
rayon = "1.10.0"
