name: Release Build and Upload

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Build Linux binary
        run: cross build --release --target x86_64-unknown-linux-gnu
      - name: Archive Linux binary
        run: |
          mkdir -p dist
          cp target/x86_64-unknown-linux-gnu/release/* dist/ || true
          cd dist
          tar -czvf ../binarize_images_linux.tar.gz *
          cd ..
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: binarize_images_linux
          path: binarize_images_linux.tar.gz

  build-windows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-gnu
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Build Windows binary
        run: cross build --release --target x86_64-pc-windows-gnu
      - name: Archive Windows binary
        run: |
          mkdir -p dist
          cp target/x86_64-pc-windows-gnu/release/* dist/ || true
          cd dist
          tar -czvf ../binarize_images_windows.tar.gz *
          cd ..
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: binarize_images_windows
          path: binarize_images_windows.tar.gz

  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: binarize_images_linux
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: binarize_images_windows
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Linux Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: binarize_images_linux.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Windows Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: binarize_images_windows.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
